### ISSUE TITLE
Unable to build project

### ISSUE THREAD

**Issue by ghost** [luudvkeulen/FinalFontasyGame#3]
PS C:\Programming\FinalFontasyGame> .\BuildDesktopForDistribution.bat

C:\Programming\FinalFontasyGame>gradlew desktop:dist
Downloading http://services.gradle.org/distributions/gradle-2.10-all.zip

Exception in thread "main" java.lang.RuntimeException: java.io.IOException: Server returned HTTP response code: 403 for URL: http://services.gradle.org/distributions/gradle-2.10-all.zip
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:78)
        at org.gradle.wrapper.Install.createDist(Install.java:47)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: http://services.gradle.org/distributions/gradle-2.10-all.zip
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1924)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
        at org.gradle.wrapper.Download.downloadInternal(Download.java:59)
        at org.gradle.wrapper.Download.download(Download.java:45)
        at org.gradle.wrapper.Install$1.call(Install.java:60)
        at org.gradle.wrapper.Install$1.call(Install.java:47)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)

**Comment by ghost** [comment]
Memes

**Comment by ghost** [comment]
Misschien kan Marcel helpen

**Comment by kndschilders** [comment]
Misschien http vervangen met https: https://stackoverflow.com/questions/64724223/gradle-error-server-returned-http-response-code-403-for-url-http-services

**Comment by ghost** [comment]
@kndschilders  Amai propere code
